apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-swaggerui
spec:
  selector:
    matchLabels:
      role: swaggerui
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-notebook
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        role: swaggerui
    spec:
      # serviceAccountName: notebook
      containers:
      - name: swaggerui
        image: swaggerapi/swagger-ui
        ports:
          - containerPort: 8080
        env:
        - name: SWAGGER_JSON_URL
          value: "notebook-http-prod:8085/swagger.json"
