apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-notebook
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      serviceAccountName: notebook
      containers:
      - name: notebook
        image: jasonblanchard/di-notebook:latest
        command: ["./nats"]
        envFrom:
        - configMapRef:
            name: notebook-config
        # livenessProbe:
        #   exec:
        #     command:
        #     - grep
        #     - -q
        #     - UP
        #     - /usr/src/app/HEALTH_STATUS
        # readinessProbe:
        #   exec:
        #     command:
        #     - grep
        #     - -q
        #     - UP
        #     - /usr/src/app/HEALTH_STATUS
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # ports:
        # - containerPort: 4000
