apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-nats
spec:
  selector:
    matchLabels:
      role: nats
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-notebook
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        role: nats
    spec:
      serviceAccountName: notebook
      containers:
      - name: notebook
        image: jasonblanchard/di-notebook:latest
        command: ["./nats"]
        envFrom:
        - configMapRef:
            name: notebook-config
