apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-grpc
spec:
  selector:
    matchLabels:
      role: grpc
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-notebook
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        role: grpc
    spec:
      serviceAccountName: notebook
      containers:
      - name: notebook
        image: jasonblanchard/di-notebook:latest
        command: ["./grpc"]
        ports:
          - containerPort: 8080
          - containerPort: 8081
        envFrom:
        - configMapRef:
            name: notebook-config
