apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- deployment-nats.yaml
- deployment-grpc.yaml
- deployment-http.yaml
- service-grpc.yaml
- service-http.yaml
- post-sync-migrations.yaml
- http-mapping.yaml
- deployment-swaggerui.yaml
- service-swaggerui.yaml
- swaggerui-mapping.yaml
commonLabels:
  app: notebook
configMapGenerator:
- name: notebook-config
  literals:
  - NATS_URL=nats://nats:4222
  - PORT=8080
