apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- deployment.yaml
- post-sync-migrations.yaml
commonLabels:
  app: notebook
configMapGenerator:
- name: notebook-config
  literals:
  - NATS_URL=nats://nats:4222
