apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa.yaml
  - deployment.yaml
commonLabels:
  app: notebook
configMapGenerator:
- literals:
  - NATS_HOST=nats://nats:4222
  name: notebook-config
