apiVersion: v1
kind: Service
metadata:
  name: notebook-grpc
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
    - name: http
      protocol: TCP
      port: 8081
  selector:
    role: grpc