version: 0.0
Resources:
  - apiLambdaFn:
      FunctionCode:
        S3Bucket: di-notebook-prod-b287d59
        S3Key: 151b34707d49e2b2745286e331b2d11da8d3b2f7/apilambda.zip
AppSpec:
  version: 0.0
  Resources:
    - apiLambdaFn:
        Type: AWS::Lambda::Function
        Properties:
          Name: "di-notebook-prod"
          Alias: "release"