version: 0.0
Resources:
  - apiLambdaFn:
      FunctionCode:
        S3Bucket: di-notebook-prod-b287d59
        S3Key: 1807f2f4a0579f840863b90117e1d054ae779a3b/apilambda.zip
AppSpec:
  version: 0.0
  Resources:
    - apiLambdaFn:
        Type: AWS::Lambda::Function
        Properties:
          Name: "di-notebook-prod"
          Alias: "release"