apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db.yaml
bases:
- ../base
commonLabels:
  environment: production
configMapGenerator:
- name: notebook-config
  behavior: merge
  literals:
  - DB_USER=postgres
  - DB_PASSWORD=vault:secret/data/di-notebook/production/app#DB_PASSWORD
  - DB_HOST=di-notebook-psql-production
  - DB_PORT=5432
  - DATABASE=di_entry
  - GITHUB_TOKEN=vault:secret/data/di-notebook/production/app#GITHUB_TOKEN
- name: notebook-http-config
  literals:
  - backend=notebook-grpc-production:8080
nameSuffix: -production
