apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db.yaml
bases:
- ../base
commonLabels:
  environment: production
configMapGenerator:
- name: notebook-config
  behavior: merge
  literals:
  - DB_USER=postgres
  - DB_PASSWORD=vault:secret/data/di-notebook/production/app#DB_PASSWORD
  - DB_HOST=di-notebook-psql-production
  - DB_PORT=5432
  - DATABASE=di_entry
  - GITHUB_TOKEN=vault:secret/data/di-notebook/production/app#GITHUB_TOKEN
  - AWS_REGION=us-east-1
  - FIREHOSE_ENTRY_REVISIONS_DELIVERY_STREAM_NAME=di-entry-revisions-stream-production
  - AWS_ACCESS_KEY_ID=vault:secret/data/di-notebook/production/app#AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY=vault:secret/data/di-notebook/production/app#AWS_SECRET_ACCESS_KEY
- name: notebook-http-config
  literals:
  - GRPC_BACKEND=notebook-grpc-production:8080
nameSuffix: -production
patchesStrategicMerge:
  - patch-http-mapping.yaml
  - patch-swaggerui-mapping.yaml
