// Code generated by sqlc. DO NOT EDIT.

package dinotebook

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID         int32
	Text       sql.NullString
	CreatorID  string
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeleteTime sql.NullTime
}
