name: post merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install pack
      run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build & push
      run: make push
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: jasonblanchard/di-deploy/.github/actions/deploy-dispatch@main
        with:
          username: ${{ secrets.DEPLOY_USERNAME }}
          token: ${{ secrets.DEPLOY_TOKEN }}
          service: notebook
          environment: production
          version: ${{ github.sha }}
