name: post merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: build & push
        run: |
          make apipush

      - name: push deployspec
        run: |
          cat deployspec.template.yaml | sed -e 's/%SHA%/'"$GITHUB_SHA"'/g' > deployspec.yaml
          cat deployspec.yaml
          make deployspec

